runtime: python27
api_version: 1
threadsafe: true 

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: './service_account_credentials.json'

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: incoming.app
  login: admin
- url: /static
  static_dir: static
- url: /.*
  script: main.app
